<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>ConsoleApp1.Program</StartupObject>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- <ItemGroup>
    <None Remove="mapa.txt" />
  </ItemGroup> -->

  <ItemGroup>
    <Content Include="mapa.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Shared\Infrastructure\ConfigurationFile\config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\ClientServerCommunication\" />
  </ItemGroup>



</Project>
